title: Star Formation Workshop 2025
description: # Workshop on Star Formation

remote_theme: daviddarnes/alembic

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

google_fonts: "Noto+Sans+JP:400,700"
