title: Star Formation Workshop 2025
description: # Workshop on Star Formation

remote_theme: andrewbanchich/forty-jekyll-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM
timezone: Asia/Tokyo

# Forty特有のコレクション設定
collections:
  projects:
    output: true
  posts:
    output: true
